/* Auto-generated file - Modifications may be overwritten */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as SettingsRouteImport } from './routes/settings.route';
import { Route as ProfileRouteImport } from './routes/profile.route';
import { Route as GuidesRouteImport } from './routes/guides.route';
import { Route as IndexRouteImport } from './routes/index.route';
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index.route';
import { Route as RecordingsIdRouteImport } from './routes/recordings/$id.route';

// Create/Update Routes

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any);

const ProfileRouteRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any);

const GuidesRouteRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRoute,
} as any);

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const RecordingsIndexRouteRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRoute,
} as any);

const RecordingsIdRouteRoute = RecordingsIdRouteImport.update({
  id: '/recordings/$id',
  path: '/recordings/$id',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/guides': {
      id: '/guides';
      path: '/guides';
      fullPath: '/guides';
      preLoaderRoute: typeof GuidesRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/recordings/$id': {
      id: '/recordings/$id';
      path: '/recordings/$id';
      fullPath: '/recordings/$id';
      preLoaderRoute: typeof RecordingsIdRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/recordings/': {
      id: '/recordings/';
      path: '/recordings';
      fullPath: '/recordings';
      preLoaderRoute: typeof RecordingsIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute;
  '/guides': typeof GuidesRouteRoute;
  '/profile': typeof ProfileRouteRoute;
  '/settings': typeof SettingsRouteRoute;
  '/recordings/$id': typeof RecordingsIdRouteRoute;
  '/recordings': typeof RecordingsIndexRouteRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute;
  '/guides': typeof GuidesRouteRoute;
  '/profile': typeof ProfileRouteRoute;
  '/settings': typeof SettingsRouteRoute;
  '/recordings/$id': typeof RecordingsIdRouteRoute;
  '/recordings': typeof RecordingsIndexRouteRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRouteRoute;
  '/guides': typeof GuidesRouteRoute;
  '/profile': typeof ProfileRouteRoute;
  '/settings': typeof SettingsRouteRoute;
  '/recordings/$id': typeof RecordingsIdRouteRoute;
  '/recordings/': typeof RecordingsIndexRouteRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/guides'
    | '/profile'
    | '/settings'
    | '/recordings/$id'
    | '/recordings';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/guides' | '/profile' | '/settings' | '/recordings/$id' | '/recordings';
  id:
    | '__root__'
    | '/'
    | '/guides'
    | '/profile'
    | '/settings'
    | '/recordings/$id'
    | '/recordings/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute;
  GuidesRouteRoute: typeof GuidesRouteRoute;
  ProfileRouteRoute: typeof ProfileRouteRoute;
  SettingsRouteRoute: typeof SettingsRouteRoute;
  RecordingsIdRouteRoute: typeof RecordingsIdRouteRoute;
  RecordingsIndexRouteRoute: typeof RecordingsIndexRouteRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  GuidesRouteRoute: GuidesRouteRoute,
  ProfileRouteRoute: ProfileRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  RecordingsIdRouteRoute: RecordingsIdRouteRoute,
  RecordingsIndexRouteRoute: RecordingsIndexRouteRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/guides",
        "/profile",
        "/settings",
        "/recordings/$id",
        "/recordings/"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/guides": {
      "filePath": "guides.route.tsx"
    },
    "/profile": {
      "filePath": "profile.route.tsx"
    },
    "/settings": {
      "filePath": "settings.route.tsx"
    },
    "/recordings/$id": {
      "filePath": "recordings/$id.route.tsx"
    },
    "/recordings/": {
      "filePath": "recordings/index.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
